baseURL = "https://xyang76.github.io/"
languageCode = "en-us"
title = "Xincheng Yang"
theme = "hugo-theme-console"

enableRobotsTXT = true
buildDrafts = false
buildFuture = true
buildExpired = true

[params]
  author = "Xincheng Yang"
  description = "PhD | Distributed Systems | Consensus"
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  animateStyle = "animate-fade-up" # Animation style for content

[params.social]
  facebook_admin = ""
  twitter = ""
  github = "https://github.com/xyang76"

[[params.navlinks]]
  name = "About"
  url = "/about/"
  
[[params.navlinks]]
  name = "Publications"
  url = "/publications/"

[[params.navlinks]]
  name = "Projects"
  url = "/projects/"
  
[[params.navlinks]]
  name = "Posts"
  url = "/posts/"
  
[[params.navlinks]]
  name = "Personal"
  url = "/personal/"

[[params.navlinks]]
  name = "CV"
  url = "/cv/"
